grammar = {
        "Program": ["PreprocessorList GlobalDeclarationList"],
        "PreprocessorList": ["PreprocessorDirective PreprocessorList", "ε"],
        "PreprocessorDirective": ["PREPROCESSOR LESS_THAN ID DOT ID GREATER_THAN"],
        "GlobalDeclarationList": ["GlobalDeclaration GlobalDeclarationList", "ε"],
        "GlobalDeclaration": ["TypeDec", "VarDec", "FunctionDec"],
        "Statement": ["ID StatementRest", "IfStatement", "WhileStatement", "CoutStatement", "BlockStatement",
                      "TypeDec"],
        "StatementRest": ["EQUALS Expression SEMICOLON", ". ID EQUALS Expression SEMICOLON", "ID SEMICOLON"],
        "IfStatement": ["if PAREN_L Expression PAREN_R Statement IfStatementRest"],
        "IfStatementRest": ["else Statement", "ε"],
        "WhileStatement": ["while PAREN_L Expression PAREN_R Statement"],
        "CoutStatement": ["cout << Expression CoutRest SEMICOLON"],
        "CoutRest": ["<< endl", "ε"],
        "BlockStatement": ["BRACE_L StatementList BRACE_R"],
        "StatementList": ["Statement StatementList", "ε"],
        "TypeDec": ["struct ID BRACE_L VarDecList BRACE_R SEMICOLON"],
        "VarDec": ["Type ID VarDecRest SEMICOLON", "ε"],
        "VarDecRest": ["EQUALS Expression", "ε"],
        "VarDecList": ["VarDec VarDecList", "ε"],
        "Type": ["int", "float", "char"],
        "FunctionDec": ["Type ID PAREN_L FormalList PAREN_R BRACE_L VarDecList StatementList return Expression SEMICOLON BRACE_R"],
        "Expression": ["LogicalOrExpression"],
        "LogicalOrExpression": ["LogicalAndExpression MoreLogicalOr"],
        "MoreLogicalOr": ["OR LogicalAndExpression MoreLogicalOr", "ε"],
        "LogicalAndExpression": ["EqualityExpression MoreLogicalAnd"],
        "MoreLogicalAnd": ["AND EqualityExpression MoreLogicalAnd", "ε"],
        "EqualityExpression": ["RelationalExpression MoreEquality"],
        "MoreEquality": ["EqualityOperator RelationalExpression MoreEquality", "ε"],
        "EqualityOperator": ["EQUAL_EQUAL", "NOT_EQUAL"],
        "RelationalExpression": ["AdditiveExpression MoreRelational"],
        "MoreRelational": ["RelationalOperator AdditiveExpression MoreRelational", "ε"],
        "RelationalOperator": ["LESS_THAN", "GREATER_THAN", "LESS_THAN_EQUAL", "GREATER_THAN_EQUAL"],
        "AdditiveExpression": ["Term MoreAdditive"],
        "MoreAdditive": ["AdditiveOperator Term MoreAdditive", "ε"],
        "AdditiveOperator": ["PLUS", "MINUS"],
        "Term": ["Factor MoreMultiplicative"],
        "MoreMultiplicative": ["MultiplicativeOperator Factor MoreMultiplicative", "ε"],
        "MultiplicativeOperator": ["PRODUCT", "DIVISION"],
        "Factor": ["ID FactorRest"],
        "FactorRest": [". ID", "PAREN_L ExpList PAREN_R", "ε"],
        "ExpList": ["Expression ExpRest", "ε"],
        "ExpRest": ["COMMA Expression ExpRest", "ε"],
        "FormalList": ["Parameter FormalRest", "ε"],
        "FormalRest": ["COMMA Parameter FormalRest", "ε"],
        "Parameter": ["Type ID"]
    }