from GrammarIdentifiers import *
parse_table = [[non_terminals["OperationInitialAxiom"], 'identificador', [non_terminals["OperationT"], non_terminals["OperationE'"]]],
          [non_terminals["OperationInitialAxiom"], 'PLUS', None],
          [non_terminals["OperationInitialAxiom"], 'TIMES', None],
          [non_terminals["OperationInitialAxiom"], 'LPAREN', [non_terminals["OperationT"], non_terminals["OperationE'"]]],
          [non_terminals["OperationInitialAxiom"], 'RPAREN', None],
          [non_terminals["OperationInitialAxiom"], 'eof', None],
          [non_terminals["OperationE'"], 'identificador', None],
          [non_terminals["OperationE'"], 'PLUS', ['PLUS', non_terminals["OperationT"], non_terminals["OperationE'"]]],
          [non_terminals["OperationE'"], 'TIMES', None],
          [non_terminals["OperationE'"], 'LPAREN', None],
          [non_terminals["OperationE'"], 'RPAREN', ['vacia']],
          [non_terminals["OperationE'"], 'eof', ['vacia']],
          [non_terminals["OperationT"], 'identificador', [non_terminals["OperationF"], non_terminals["OperationT'"]]],
          [non_terminals["OperationT"], 'PLUS', None],
          [non_terminals["OperationT"], 'TIMES', None],
          [non_terminals["OperationT"], 'LPAREN', [non_terminals["OperationF"], non_terminals["OperationT'"]]],
          [non_terminals["OperationT"], 'RPAREN', None],
          [non_terminals["OperationT"], 'eof', None],
          [non_terminals["OperationT'"], 'identificador', None],
          [non_terminals["OperationT'"], 'PLUS', ['vacia']],
          [non_terminals["OperationT'"], 'TIMES', ['TIMES', non_terminals["OperationF"], non_terminals["OperationT'"]]],
          [non_terminals["OperationT'"], 'LPAREN', None],
          [non_terminals["OperationT'"], 'RPAREN', ['vacia']],
          [non_terminals["OperationT'"], 'eof', ['vacia']],
          [non_terminals["OperationF"], 'identificador', ['identificador']],
          [non_terminals["OperationF"], 'PLUS', None],
          [non_terminals["OperationF"], 'TIMES', None],
          [non_terminals["OperationF"], 'LPAREN', ['LPAREN', non_terminals["OperationInitialAxiom"], 'RPAREN']],
          [non_terminals["OperationF"], 'RPAREN', None],
          [non_terminals["OperationF"], 'eof', None],
          ]